Models/Interview.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Project.Skillz.Models
{   
    public enum Assess
    {
        Subjective,
        Objective,
        Both
    }
    public enum skill
    {
        Begineer,
        Intermediate,
        Advanced
    }
    public class Interview
    {

        public int id { get; set; }

        [Display(Name = "Interview Name")]
        [Required]
        public string InterviewName { get; set; }
        [Display(Name = "Skill Level")]
        [Required]
        public skill SkillLevel { get; set; }
        [Display(Name = "Assessment Modes")]
        [Required]
        public Assess AssessmentModes { get; set; }
        [Display(Name ="Status")]
        public string Status { get; set; }
        public string Questions { get; set; }
    }

    public class DashBoardDbContext : DbContext
    {
       public DbSet<Interview> interviews { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Skillz.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/InterviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Skillz.Models;

namespace Project.Skillz.Controllers
{
    public class InterviewController : Controller
    {
        public static List<Interview> interviews = new List<Interview>();
        // GET: Interview
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Table()
        {
            
            return View(interviews);
        }
        
        public ActionResult Create()
        {
            Interview temp1 = new Interview();
            return View(temp1);

        }
        [HttpPost]
        public ActionResult Create(Interview interview)
        {
            if (ModelState.IsValid)
            {
                interview.id = interviews.Count() + 1;
                interviews.Add(interview);
                return RedirectToAction("Table");
            }
            return RedirectToAction("Table");
        }

        public ActionResult New()
        {
            Interview temp1 = new Interview();
            return View(temp1);
        }
        [HttpPost]
        public ActionResult New(Interview interview)
        {
            interview.id = interviews.Count() + 1;
            interviews.Add(interview);
            return RedirectToAction("Table");
        }
    }
}

Controllers/InterviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project.Skillz.Models;

namespace Project.Skillz.Controllers
{
    public class InterviewsController : Controller
    {
        private DashBoardDbContext db = new DashBoardDbContext();

        // GET: Interviews
        public ActionResult Index()
        {
            return View(db.interviews.ToList());
        }

        // GET: Interviews/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interview interview = db.interviews.Find(id);
            if (interview == null)
            {
                return HttpNotFound();
            }
            return View(interview);
        }

        // GET: Interviews/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Interviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,InterviewName,SkillLevel,AssessmentModes,Status,Questions")] Interview interview)
        {
            if (ModelState.IsValid)
            {
                interview.Status = "Draft";
                interview.Questions = "Configure";
                db.interviews.Add(interview);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(interview);
        }

        // GET: Interviews/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Interview interview = db.interviews.Find(id);
        //    if (interview == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(interview);
        //}

        // POST: Interviews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "id,InterviewName,SkillLevel,AssessmentModes,Status,Questions")] Interview interview)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(interview).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(interview);
        //}

        // GET: Interviews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interview interview = db.interviews.Find(id);
            if (interview == null)
            {
                return HttpNotFound();
            }
            return View(interview);
        }

        // POST: Interviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Interview interview = db.interviews.Find(id);
            db.interviews.Remove(interview);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Interview/Create.cshtml
@model Project.Skillz.Models.Interview

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Interview</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.selected, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.selected)
                    @Html.ValidationMessageFor(model => model.selected, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.serialNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.serialNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.serialNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InterviewName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InterviewName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InterviewName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SkillLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SkillLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SkillLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssessmentModes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AssessmentModes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AssessmentModes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Questions, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Questions, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Questions, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Interview/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<h3 style="text-align: left; font: normal normal normal 14px/12px Lucida Console; letter-spacing: 0px; color: #BE1B35; opacity: 1;">Dashboard /</h3>
<h2 style="text-align: left; font: normal normal normal 20px/12px Lucida Console; letter-spacing: 0px; color: #73737A; opacity: 1;">Interviews</h2>
<div class="table-responsive" style="border: 1px solid #707070; opacity: 1;">
    <table class="table table-condensed">
        <thead style="        background: #F0F0F0 0% 0% no-repeat padding-box; text-align: left;
        font: normal normal normal 14px/12px Lucida Console;
        letter-spacing: 0px;
        color: #73737A;
        opacity: 1;
         ">
            <tr>
                <th><input type="checkbox" name="" /></th>
                <th>#</th>
                <th>Interview Name</th>
                <th>Skill Level</th>
                <th>Assessment Mode</th>
                <th>Status</th>
                <th>Questions</th>
            </tr>
        </thead>
        <tbody style="text-align: left; font: normal normal normal 14px/12px Lucida Console; letter-spacing: 0px; color: #73737A; opacity: 1;">
            <tr>
                <td><input type="checkbox" name="" /></td>
                <td>1</td>
                <td><a href="">ASP.Net MVC Developer</a></td>
                <td>Beginner</td>
                <td>Objective</td>
                <td>Draft</td>
                <td>Configure</td>
            </tr>

            <tr>
                <td><input type="checkbox" name="" /></td>
                <td>1</td>
                <td><a href="">Marketing Executive</a></td>
                <td>Advanced</td>
                <td>Objective</td>
                <td>Published</td>
                <td>Configure</td>
            </tr>

            <tr>
                <td><input type="checkbox" name="" /></td>
                <td>1</td>
                <td><a href="">Sales Executive</a></td>
                <td>Beginner</td>
                <td>Subjective</td>
                <td>Discontinued</td>
                <td>Configure</td>
            </tr>

            <tr>
                <td><input type="checkbox" name="" /></td>
                <td>1</td>
                <td><a href="">General Manager</a></td>
                <td>Intermediate</td>
                <td>Objective</td>
                <td>Draft</td>
                <td>Configure</td>
            </tr>

            <tr>
                <td><input type="checkbox" name="" /></td>
                <td>1</td>
                <td><a href="">ASP.Net MVC</a></td>
                <td>Beginner</td>
                <td>Objective</td>
                <td>Draft</td>
                <td>Configure</td>
            </tr>
            <tr>
                <td><input type="checkbox" name="" /></td>
                <td>1</td>
                <td><a href="">ASP.Net MVC</a></td>
                <td>Beginner</td>
                <td>Objective</td>
                <td>Draft</td>
                <td>Configure</td>
            </tr>
            <tr>
                <td><input type="checkbox" name="" /></td>
                <td>1</td>
                <td><a href="">ASP.Net MVC</a></td>
                <td>Beginner</td>
                <td>Objective</td>
                <td>Draft</td>
                <td>Configure</td>
            </tr>
            <tr>
                <td><input type="checkbox" name="" /></td>
                <td>1</td>
                <td><a href="">ASP.Net MVC</a></td>
                <td>Beginner</td>
                <td>Objective</td>
                <td>Draft</td>
                <td>Configure</td>
            </tr>
            <tr>
                <td><input type="checkbox" name="" /></td>
                <td>1</td>
                <td><a href="">ASP.Net MVC</a></td>
                <td>Beginner</td>
                <td>Objective</td>
                <td>Draft</td>
                <td>Configure</td>
            </tr>
            <tr>
                <td><input type="checkbox" name="" /></td>
                <td>1</td>
                <td><a href="">ASP.Net MVC</a></td>
                <td>Beginner</td>
                <td>Objective</td>
                <td>Draft</td>
                <td>Configure</td>
            </tr>
            <tr>
                <td><input type="checkbox" name=""/></td>
                <td>1</td>
                <td><a href="">ASP.Net MVC</a></td>
                <td>Beginner</td>
                <td>Objective</td>
                <td>Draft</td>
                <td>Configure</td>
            </tr>
        </tbody>

    </table>
</div>

Views/Interview/New.cshtml
@model Project.Skillz.Models.Interview
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>New</title>
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")

    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
</head>
<body class="container">
    <form>
        <div class="form-group">
            <label for="usr" style="text-align: left; font: normal normal normal 14px/12px Lucida Console; letter-spacing: 0px; color: #73737A; opacity: 1;">Interview Name</label>
            <input type="text" class="form-control" id="usr" style="background: #FFFFFF 0% 0% no-repeat padding-box; border: 1px solid #707070; border-radius: 7px; opacity: 1;" placeholder="Enter interview name.">
        </div>
    <div class="form-group">
        <label for="sel1" style="text-align: left; font: normal normal normal 14px/12px Lucida Console; letter-spacing: 0px; color: #73737A; opacity: 1;">Skill Level</label>
        <select class="form-control" style="background: #FFFFFF 0% 0% no-repeat padding-box; border: 1px solid #707070; border-radius: 7px; opacity: 1;" id="sel1">
            <option>Begineer</option>
            <option>Intermediate</option>
            <option>Advanced</option>
        </select>
    </div>
    <label for="assmode" style="text-align: left; font: normal normal normal 14px/12px Lucida Console; letter-spacing: 0px; color: #73737A; opacity: 1;">Assesment Modes</label>
    <div class="form-group" id="assmode">
        <label class="radio-inline"><input type="radio" name="optradio" checked>Subjective</label>
        <label class="radio-inline"><input type="radio" name="optradio">Objective</label>
        <label class="radio-inline"><input type="radio" name="optradio">Both</label>
    </div>
        </form>
</body>
</html>

Views/Interview/Table.cshtml
@model IEnumerable<Project.Skillz.Models.Interview>
@using Project.Skillz.Models;
@{
    ViewBag.Title = "Table";
}

<h3 style="text-align: left; font: normal normal normal 14px/12px Lucida Console; letter-spacing: 0px; color: #BE1B35; opacity: 1;">Dashboard /</h3>
<h2 style="text-align: left; font: normal normal normal 20px/12px Lucida Console; letter-spacing: 0px; color: #73737A; opacity: 1;">Interviews</h2>
<div class="input-group" style="width:371px; text-align:left">
    <input type="text" class="form-control" placeholder="Search">
    <div class="input-group-btn">
        <button class="btn btn-default" type="button">
            <i class="glyphicon glyphicon-search"></i>
        </button>
    </div></div>
<script>
    $(document).ready(function () {
        $('#select_all').click(function (e) {
            $(this).closest('table').find('td input:checkbox').prop('checked', this.checked);
        });
    });
</script>
<p style="text-align: right; font: normal normal normal 14px/12px Lucida Console; letter-spacing: 0px; color: #FFFFFF; opacity: 1;">
    <button type="button" class="btn btn-danger" style="border-radius:20px;"><span class="glyphicon glyphicon-plus">&nbsp;</span>@Html.ActionLink("New Interview","#", new { Style = "color:#FFFFFF" }, new { @data_toggle = "modal", @data_target = "#YourModalId" })</button>
    <button type="button" class="btn" style="border-radius:20px;"><span class="glyphicon glyphicon-remove">&nbsp;</span>@Html.ActionLink("Delete Selected", "Delete", "Interview", new { Style = "color:#2D2121" })</button>
    <button type="button" class="btn" style="border-radius:20px;"><span class="glyphicon glyphicon-option-vertical">&nbsp;</span>@Html.ActionLink("More Options", "#", "Interview", new { Style = "color:#2D2121" })</button>
</p>
<div id="YourModalId" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
               
            </div>
            <div class="modal-body container">
                <form class="container" id="create1">
                    <div class="form-group">
                        <label for="usr" style="text-align: left; font: normal normal normal 14px/12px Lucida Console; letter-spacing: 0px; color: #73737A; opacity: 1;">Interview Name</label>
                        <input type="text" class="form-control" id="usr" style="width:400px;background: #FFFFFF 0% 0% no-repeat padding-box; border: 1px solid #707070; border-radius: 7px; opacity: 1;" placeholder="Enter interview name.">
                    </div>
                    <div class="form-group">
                        <label for="sel1" style="text-align: left; font: normal normal normal 14px/12px Lucida Console; letter-spacing: 0px; color: #73737A; opacity: 1;">Skill Level</label>
                        <select class="form-control" style="width:260px;background: #FFFFFF 0% 0% no-repeat padding-box; border: 1px solid #707070; border-radius: 7px; opacity: 1;" id="sel1">
                            <option>Begineer</option>
                            <option>Intermediate</option>
                            <option>Advanced</option>
                        </select>
                    </div>
                    <label for="assmode" style="text-align: left; font: normal normal normal 14px/12px Lucida Console; letter-spacing: 0px; color: #73737A; opacity: 1;">Assesment Modes</label>
                    <div class="form-group" id="assmode">
                        <label class="radio-inline"><input type="radio" name="optradio" checked>Subjective</label>
                        <label class="radio-inline"><input type="radio" name="optradio">Objective</label>
                        <label class="radio-inline"><input type="radio" name="optradio">Both</label>
                    </div>
                </form>   
            </div>
            <div class="modal-footer">
                <button type="submit"form="create1" class="btn btn-default" data-dismiss="modal" style="background: #B70320 0% 0% no-repeat padding-box; box-shadow: 0px 3px 6px #00000029; border-radius: 32px; opacity: 1;">Save Changes</button>
            </div>
        </div>

    </div>
</div>
<table id="skillz" class="table table-condensed" style="background: #FFFFFF 0% 0% no-repeat padding-box; border: 1px solid #707070; opacity: 1;">
    <thead style="        background: #F0F0F0 0% 0% no-repeat padding-box;
        text-align: left;

        font: normal normal normal 14px /12px Lucida Console;
        letter-spacing: 0px;
        color: #73737A;
        opacity: 1;">
        <tr>

            <th><input type="checkbox" id="select_all" name="select_invoice" />
                
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.InterviewName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SkillLevel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AssessmentModes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Questions)
            </th>
            <th></th>

        </tr>
    </thead>
    <tbody style="text-align: left; font: normal normal normal 14px/12px Lucida Console; letter-spacing: 0px; color: #73737A; opacity: 1;">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <input type="checkbox"  />
                </td>
            
                <td>
                    @Html.DisplayFor(modelItem => item.InterviewName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SkillLevel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AssessmentModes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Questions)
                </td>
                
            </tr>
        }
    </tbody>
</table>

Views/Interviews/Create.cshtml
@model Project.Skillz.Models.Interview

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Interview</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.InterviewName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InterviewName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InterviewName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SkillLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.SkillLevel, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SkillLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssessmentModes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.AssessmentModes, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AssessmentModes, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Interviews/Index.cshtml
@model IEnumerable<Project.Skillz.Models.Interview>

@{
    ViewBag.Title = "Index";
}
<link href="~/Content/sty.css" rel="stylesheet" />
<h3 class="myh3">Dashboard /</h3>
<h2 class="myh2">Interviews</h2>
<script>
    $(document).ready(function () {
        $('#select_all').click(function (e) {
            $(this).closest('table').find('td input:checkbox').prop('checked', this.checked);
        });
    });
</script>

<p style="text-align: right; font: normal normal normal 14px/12px Lucida Console; letter-spacing: 0px; color: #FFFFFF; opacity: 1;">
    <button type="button" class="btn btn-danger" style="border-radius:20px;"><span class="glyphicon glyphicon-plus">&nbsp;</span>@Html.ActionLink("New Interview", "Create","Interviews", new { Style = "color:#FFFFFF" }, new { @data_toggle = "modal", @data_target = "#myModal" })</button>
    <button type="button" class="btn" style="border-radius:20px;"><span class="glyphicon glyphicon-remove">&nbsp;</span>@Html.ActionLink("Delete Selected", "Delete", "Interviews", new { Style = "color:#2D2121" })</button>
    <button type="button" class="btn" style="border-radius:20px;"><span class="glyphicon glyphicon-option-vertical">&nbsp;</span>@Html.ActionLink("More Options", "","", new { Style = "color:#2D2121" })</button>
</p>
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
            </div>
            <div class="modal-body">
                <p>Some text in the modal.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<table class="table table-condensed mytable">
    <thead class="mythead">
        <tr>
            <th>
                <input type="checkbox" id="select_all" name="select_invoice" />
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InterviewName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SkillLevel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AssessmentModes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Questions)
            </th>
          
        </tr>
    </thead>
    <tbody class="mytbody">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <input type="checkbox" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InterviewName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SkillLevel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AssessmentModes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Questions)
                </td>
                
            </tr>


        }</tbody>

</table>